name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Trigger deploy only on main branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: vijaya-23
        export_default_credentials: true

    - name: Deploy to App Engine
      run: gcloud app deploy --quiet
