name: Deploy to App Engine

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to GAE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: zippy-rarity-468010-a3
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to App Engine
      run: gcloud app deploy --quiet
