name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: zippy-rarity-468010-a3
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=gcr.io/zippy-rarity-468010-a3/my-app
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-app \
            --image=gcr.io/zippy-rarity-468010-a3/my-app \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated
